config/routes.rb
SaintsSinners::Application.routes.draw do

  #Omniauth-Facebook for Users
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :path => "u", :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" }
  match 'auth/:provider/callback', to: 'auth#create'
  match 'auth/failure', to: redirect('/')

  #Management of Users
  resources :users

  #Devise for Admins
  devise_for :admin_users, path_names: {sign_in: "login", sign_out: "logout"}, :path => "d", :controllers => { :registrations => "admin_users/registrations", :sessions => "admin_users/sessions" }

  #Management of Admins
  resources :admin_users

  root :to => 'welcome#index'
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base

  rolify  
  #resourcify

  #has_and_belongs_to_many :roles, :join_table => :users_roles, :foreign_key => "user_id"
  has_many :user_roles, :foreign_key => :user_id
  has_and_belongs_to_many :roles, :class_name => "Role", :join_table => :users_roles, :foreign_key => :user_id

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :active
  attr_accessible :temporal_roles
  attr_accessor :temporal_roles
  
  validates :email, :uniqueness => true
  validates :username, :uniqueness => true

  def get_roles
    @temporal_roles = roles.collect{ |role| role.name }.join(", ")
  end

  def banned?
    !active
  end

  def self.get_editable_admins_except(admin_id)
    joins(:roles).where("roles.name <> ? AND admin_users.id <> ?", "admin", admin_id).group(:id)
  end
  
end

app/controllers/admin_users/registrations_controller.rb
class AdminUsers::RegistrationsController < Devise::RegistrationsController

end

app/controllers/admin_users/sessions_controller.rb
class AdminUsers::SessionsController < Devise::SessionsController

  protected

      def after_sign_in_path_for(resource)
        if resource.banned?
          sign_out resource
          flash.delete(:notice)
          flash[:error] = "This account has been suspended."
          root_path
        else
          super
        end
      end

end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

  before_filter :authenticate_admin_user!
  before_filter :authorize_admin_user_manager

  def index
    @admin_users = AdminUser.get_editable_admins_except(current_admin_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_users }
    end
  end

  def show
    @admin_user = AdminUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_user }
    end
  end

  def new
    @admin_user = AdminUser.new
    @required_password = true

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_user }
    end
  end

  def edit
    @admin_user = AdminUser.find(params[:id])

    if @admin_user.has_role? :admin
      flash[:error] = "Access denied"
      redirect_to root_url
    end

    @admin_user.get_roles
    @required_password = false
  end

  def create
    @admin_user = AdminUser.new(params[:admin_user])
    @required_password = true

    roles = []
    if can? :manage, Role
      roles = params[:admin_user][:temporal_roles].split(",")
    end
    params[:admin_user].delete(:temporal_roles)

    respond_to do |format|
      if @admin_user.save
        if can? :manage, Role
          roles.map{ |role|
            @admin_user.add_role role.strip
          }
        end

        format.html { redirect_to @admin_user, notice: 'Admin was successfully created.' }
        format.json { render json: @admin_user, status: :created, location: @admin_user }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @admin_user = AdminUser.find(params[:id])
    @required_password = false

    if @admin_user.has_role? :admin
      flash[:error] = "Access denied"
      redirect_to root_url
    end

    roles = []
    if can? :manage, Role
      roles = params[:admin_user][:temporal_roles].split(",")
    end
    params[:admin_user].delete(:temporal_roles)

    if params[:admin_user][:password].blank?
      params[:admin_user].delete(:password)
      params[:admin_user].delete(:password_confirmation)
    end

    respond_to do |format|
      if @admin_user.update_attributes(params[:admin_user])
        if can? :manage, Role
          @admin_user.roles.destroy_all

          roles.map{ |role|
            @admin_user.add_role role.strip
          }
        end

        format.html { redirect_to @admin_user, notice: 'Admin was successfully updated.' }
        format.json { head :no_content }
      else
        @admin_user.get_roles
        format.html { render action: "edit" }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @admin_user = AdminUser.find(params[:id])
    @admin_user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end

  def authorize_admin_user_manager
    if !can? :manage, AdminUser
      flash[:error] = "Access denied"
      redirect_to root_url
    end
  end

end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/_form.html.erb
<%= simple_form_for @admin_user, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :username, :required => true %>
  <%= f.input :email, :required => true %>
  <%= f.input :password, :required => @required_password %>
  <%= f.input :password_confirmation, :required => @required_password %>

  <% if can? :manage, Role %>
  	<%= f.input :temporal_roles, :label => "Roles" %>
    <%= f.input :active %>
  <% end %>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin_users/edit.html.erb
<h1>Editing admin_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin_users/index.html.erb
<h1>Administrators</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Username</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_users.each do |admin_user| %>
  <tr>
    <td><%= admin_user.email %></td>
    <td><%= admin_user.username %></td>
    <td><%= print_yes_or_no admin_user.active %></td>
    <td><%= link_to 'Show', admin_user %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(admin_user) %></td>
    <td><%= link_to 'Destroy', admin_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Admin user', new_admin_user_path %>

app/views/admin_users/new.html.erb
<h1>New admin_user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @admin_user.email %>
</p>

<p>
  <b>Username:</b>
  <%= @admin_user.username %>
</p>


<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>