config/routes.rb
SaintsSinners::Application.routes.draw do

  #Omniauth-Facebook for Users
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :path => "u", :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" }
  match 'auth/:provider/callback', to: 'auth#create'
  match 'auth/failure', to: redirect('/')

  #Management of Users
  resources :users

  #Devise for Admins
  devise_for :admin_users, path_names: {sign_in: "login", sign_out: "logout"}, :path => "d", :controllers => { :registrations => "admin_users/registrations", :sessions => "admin_users/sessions" }

  #Management of Admins
  resources :admin_users

  root :to => 'welcome#index'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  	protect_from_forgery

  	#before_filter :authenticate_user!
	before_filter :banned?

	rescue_from CanCan::AccessDenied do |exception|
		flash[:error] = "Access denied"
		redirect_to root_url
	end
	
	def banned?
		if current_user.present? && current_user.banned?
		  sign_out current_user
          flash.delete(:notice)
		  flash[:error] = "This account has been suspended."
		  root_path
		elsif current_admin_user.present? && current_admin_user.banned?
		  sign_out current_admin_user
          flash.delete(:notice)
		  flash[:error] = "This account has been suspended."
		  root_path
		end
	end

	def current_ability
		@current_ability ||= Ability.new(current_admin_user)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def print_yes_or_no(value)
		value ? "Yes" : "No"
	end

end

app/views/application/_menu_admin_users.html.erb
<% unless admin_user_signed_in? %>
	<%=link_to "Admin Login", new_admin_user_session_path %>
<% else %>
	<%= link_to "Welcome, Admin: #{current_admin_user.username}", edit_admin_user_registration_path %>
	
	<% if can? :manage, AdminUser %>
		| <%= link_to "Manage Admins", admin_users_path %>
	<% end %>

	<% if can? :manage, User %>
		| <%= link_to "Manage Users", users_path %>
	<% end %>

	| <%= link_to "Log out from Admin", destroy_admin_user_session_path, method: :delete, id: "sign_out" %>
<% end %>

app/views/application/_menu_users.html.erb
<% unless user_signed_in? %>
	<%=link_to "Login", new_user_session_path %>
	|
	<%= link_to "Login with Facebook", "/auth/facebook", id: "sign_in" %>
<% else %>
	<%= link_to "Welcome, #{current_user.username}", edit_user_registration_path %>
	|
	<%= link_to "Log out", destroy_user_session_path, method: :delete, id: "sign_out" %>
<% end %>